### ISSUE TITLE
Aggregate new samples to previous analysis

### ISSUE THREAD

**Issue by geocarvalho** [gagneurlab/FRASER#89]
Hi, thanks for making FRASER open-source.
I ran FRASER on 250 samples and want to add new samples to the analysis.
How do you guys recommend running a new BAM file and aggregating the counts to the previous counts from the first project?

Sorry to ask in the issues session, but I couldn't find any e-mail for that.
Thank you!

**Comment by AtaJadidAhari** [comment]
Hi @geocarvalho,

When you add a new sample the following steps happen if `recount=True`:

1. FRASER reads the split_reads for already counted samples from cached data
2. FRASER counts the split_reads for newly added samples
3. FRASER merges the split_reads and creates an updated spliceSites object 
4. FRASER counts the non_split_reads for all samples using the new spliceSites

Since adding new sample updates the spliceSites, We have to recount the non_split_reads for all samples. 
We are thinking of optimizing this part and making it faster but unfortunately right now there is no other way and you have to recount the non_split_reads for all samples. 

Best,

Ata

**Comment by geocarvalho** [comment]
Hi @AtaJadidAhari, I have a question about whether I need to keep the BAM files for all the samples when I need to rerun the analysis with a new sample. In the documentation, there is a topic titled "Creating a FraserDataSet from existing count matrices", but I'm unsure how to create the `junctionCts` and `spliceSiteCts`, and whether it's necessary to have all the BAM files available.

**Comment by AtaJadidAhari** [comment]
Hi @geocarvalho ,
Unfortunately you need the bam files to count the non-split reads on the new junctions that will probably be added by aggregating new samples. 
For future references, running `snakemake exportCounts --rerun-triggers mtime` from DROP will create the required external files as explained in the [documentation](https://gagneurlab-drop.readthedocs.io/en/latest/prepare.html#aberrant-splicing).

**Comment by geocarvalho** [comment]
Thanks, @AtaJadidAhari. That is a lot of space in my case.
I'm unable to run DROP on my environment, so I was trying to use the FRASER script.
